name: Python Package using Conda

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: drft
        environment-file: environment.yml
        python-version: "3.10"
        auto-activate-base: false

    - name: Test with pytest
      shell: bash -el {0}
      run: |
        pytest -v
